watch_stylesheet: true
watch_config: true
debug: false
update_check: true
show_systray: true

glazewm:
  start_command: "glazewm.exe start"
  stop_command: "glazewm.exe command wm-exit"
  reload_command: "glazewm.exe command wm-exit && glazewm.exe start"

bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      align: "center"
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#a6e3a1"
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
      auto_hide: false
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 4
      left: 3
      bottom: 0
      right: 19
    widgets:
      left: ["home", "glazewm_workspaces"]
      center: ["clock"]
      right:
        [
          "glazewm_binding_mode",
          "memory",
          "disk",
          "wifi",
          "volume",
          "bluetooth",
          "battery",
          "notifications",
          "power_menu",
        ]

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: " 󰝜 "
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "~\\Downloads" }
        - { title: "Documents", path: "~\\Documents" }
        - { title: "Pictures", path: "~\\Pictures" }
        - { title: "Videos", path: "~\\Videos" }
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "normal"
      border_color: "#DAF7A6"
      alignment: "left"
      offset_left: 4
      offset_top: 0

  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: true

  glazewm_binding_mode:
    type: "glazewm.binding_mode.GlazewmBindingModeWidget"
    options:
      hide_if_no_active: true
      label_if_no_active: "NBM"
      default_icon: ""
      icons:
        none: ""
        resize: ""
        pause: ""
      binding_modes_to_cycle_through: ["none", "resize", "pause"]
      callbacks:
        on_left: "next_binding_mode"
        on_middle: "toggle_label"
        on_right: "disable_binding_mode"

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "  {virtual_mem_percent}%"
      label_alt: "  {virtual_mem_outof}"
      update_interval: 10000
      hide_decimal: true
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "  "
      label_alt: "  "
      decimal_display: 0
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
        show_label_name: false
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#DAF7A6"
        alignment: "center"
      callbacks:
        on_left: "toggle_group"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d-%b %I:%M:%S %p}"
      label_alt: "{%A, %B %d. %Y %H:%M}"
      timezones: []
      calendar:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#DAF7A6"
        alignment: "center"
        direction: "down"
        offset_top: 0
        offset_left: 0
        show_holidays: true
        show_week_numbers: true

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon}"
      label_alt: " {wifi_icon} {wifi_name} {wifi_strength}%"
      ethernet_label: " {wifi_icon} "
      ethernet_label_alt: " {wifi_icon} {wifi_name}"
      ethernet_icon: ""
      update_interval: 32000
      wifi_icons: ["󰤮", "󰤟", "󰤢", "󰤥", "󰤨"]
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:network"
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: " {icon}  {level}"
      label_alt: "{volume}"
      volume_icons: ["🔇", "", "", "", ""]
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#DAF7A6"
        alignment: "center"
        direction: "down"
        offset_top: 0
        show_apps: true
        show_app_labels: false
        show_app_icons: true
        show_apps_expanded: false
      callbacks:
        on_right: "toggle_mute"

  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: " {icon} "
      label_alt: "{device_name}"
      label_no_device: "NDC"
      label_device_separator: ", "
      icons:
        bluetooth_on: "󰂯"
        bluetooth_off: "󰂲"
        bluetooth_connected: "󰂱"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: " {icon} {percent}%"
      label_alt: " {icon} {percent}% | time: {time_remaining}"
      hide_unsupported: true
      update_interval: 60000
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: ""
        icon_critical: ""
        icon_low: ""
        icon_medium: ""
        icon_high: ""
        icon_full: ""

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "  {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "clear_notifications"
        on_middle: "toggle_label"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: true
      blur: false
      blur_background: true
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["", "Shut Down"]
        restart: ["", "Restart"]
        signout: ["󰍃", "Sign out"]
        hibernate: ["", "Hibernate"]
        sleep: ["⏾", "Sleep"]
        cancel: ["", "Cancel"]
