DISABLE:
  - COPYPASTE
  - SPELL

SARIF_REPORTER: true

LUA_LUACHECK_ARGUMENTS: "--globals vim"

POWERSHELL_PSSCRIPTANALYZER_FILTER_REGEX_INCLUDE: ".*"
POWERSHELL_PSSCRIPTANALYZER_DISABLE_ERRORS_IF_LESS_THAN: 0
POWERSHELL_PSSCRIPTANALYZER_ARGUMENTS: "--ExcludeRule PSUseBOMForUnicodeEncodedFile"
