[tools]
gh = "2.89.0"
uv = "0.11.6"
"pipx:pre-commit" = "4.5.1"
chezmoi = "2.70.1"
bats = { version = "1.13.0", os = ["linux", "macos"] }

[tasks.pre-commit-install]
run = "pre-commit install"

[tasks.pre-commit]
run = "pre-commit run --all-files --show-diff-on-failure"
run_windows = "set SKIP=source-tests&& pre-commit run --all-files --show-diff-on-failure"
