#!/bin/zsh

# -e: exit on error
# -u: exit on unset variables
set -eu

# Run original command
/opt/homebrew/bin/7zz "$@"

# Create encrypted directory
encrypted_dir="$(dirname "$2")/encrypted"
mkdir -p "$encrypted_dir"

# Encrypt the archive
/opt/homebrew/bin/gpg \
  --encrypt \
  --recipient "0x65CAF46236C4AE25" \
  --output "$encrypted_dir/$(basename "$2").gpg" \
  "$2"

# Delete encrypted archives older than 3 days
find "$encrypted_dir" -type f -name "*.7z.gpg" -mtime +3 -exec rm -f {} \;

