name: BadgeSort

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  badgesort:
    name: BadgeSort
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Generate badges
        uses: docker://ghcr.io/chipwolf/badgesort@sha256:a0b74fd865d8c93040f74c865272421e6ba4cdeb4b882990548f90e2debed04a
        with:
          slugs: >-
            bitwarden
            docker
            git
            githubactions
            homebrew
            linux
            macos
            neovim
            python
            tmux
            wezterm
            zsh
          style: for-the-badge
          sort: hilbert
          format: markdown
          output: README.md

      - name: Commit badge updates
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore: update badges"
          file_pattern: README.md
