---
name: Source tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  source-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install mise (Unix)
        if: runner.os != 'Windows'
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        shell: bash

      - name: Install mise (Windows)
        if: runner.os == 'Windows'
        run: |
          irm https://mise.run/ps1 | iex
          "$env:USERPROFILE\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -q
          sudo apt-get install -yq bats
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
        shell: bash

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y chezmoi
        shell: pwsh

      - name: Install toolchain
        run: mise install

      - name: Run tests via pre-commit
        run: mise run pre-commit
